// Loads products.json (auto-generated by build.js on every Netlify deploy)
// and renders the full gallery with filters + lightbox.
// Also powers the featured samples on the home page.

let catalog = null;
let allImages = [];

async function loadCatalog() {
  if (catalog) return catalog;
  const res = await fetch('data/products.json');
  catalog = await res.json();
  allImages = [];
  catalog.categories.forEach(cat => {
    cat.images.forEach(src => allImages.push({ src, category: cat.id }));
  });
  return catalog;
}

// ===== Products page =====
async function initProductsPage() {
  const container = document.getElementById('products-container');
  const filterBar = document.getElementById('filter-bar');
  if (!container) return;

  const data = await loadCatalog();

  // Filter buttons
  let btns = '<button class="filter-btn active" data-filter="all">All</button>';
  data.categories.forEach(cat => {
    btns += `<button class="filter-btn" data-filter="${cat.id}">${cat.name} <span style="opacity:0.5">(${cat.count})</span></button>`;
  });
  filterBar.innerHTML = btns;

  // Category sections with image grids
  let html = '';
  data.categories.forEach(cat => {
    html += `<div class="category-section" data-category="${cat.id}">`;
    html += `<h2>${cat.name}${cat.price ? ` <span class="price-range">${cat.price}</span>` : ''}</h2>`;
    html += `<p class="category-count">${cat.count} piece${cat.count !== 1 ? 's' : ''}</p>`;
    html += '<div class="product-grid">';
    cat.images.forEach(src => {
      const idx = allImages.findIndex(a => a.src === src);
      html += `<div class="product-card" data-index="${idx}"><img src="${encodeURI(src)}" alt="${cat.name}" loading="lazy"></div>`;
    });
    html += '</div></div>';
  });
  container.innerHTML = html;

  fadeInImages(container);

  // Filter click
  filterBar.addEventListener('click', e => {
    const btn = e.target.closest('.filter-btn');
    if (!btn) return;
    filterBar.querySelectorAll('.filter-btn').forEach(b => b.classList.remove('active'));
    btn.classList.add('active');
    const f = btn.dataset.filter;
    container.querySelectorAll('.category-section').forEach(s => {
      s.style.display = (f === 'all' || s.dataset.category === f) ? '' : 'none';
    });
  });

  // Lightbox
  const lb = document.getElementById('lightbox');
  const lbImg = document.getElementById('lightbox-img');
  let cur = 0;

  const open = i => { cur = i; lbImg.src = encodeURI(allImages[cur].src); lb.classList.add('open'); document.body.style.overflow = 'hidden'; };
  const close = () => { lb.classList.remove('open'); document.body.style.overflow = ''; };
  const go = d => { cur = (cur + d + allImages.length) % allImages.length; lbImg.src = encodeURI(allImages[cur].src); };

  container.addEventListener('click', e => { const c = e.target.closest('.product-card'); if (c) open(+c.dataset.index); });
  document.getElementById('lightbox-close').addEventListener('click', close);
  document.getElementById('lightbox-prev').addEventListener('click', () => go(-1));
  document.getElementById('lightbox-next').addEventListener('click', () => go(1));
  lb.addEventListener('click', e => { if (e.target === lb) close(); });
  document.addEventListener('keydown', e => {
    if (!lb.classList.contains('open')) return;
    if (e.key === 'Escape') close();
    if (e.key === 'ArrowLeft') go(-1);
    if (e.key === 'ArrowRight') go(1);
  });
}

// ===== Home page featured samples =====
async function initFeaturedGrid() {
  const grid = document.getElementById('featured-grid');
  if (!grid) return;

  const data = await loadCatalog();

  // Show first image from up to 6 categories
  let html = '';
  data.categories.slice(0, 6).forEach(cat => {
    if (cat.images.length === 0) return;
    html += `<a href="products.html" class="postcard">`;
    html += `<img class="postcard__img" src="${encodeURI(cat.images[0])}" alt="${cat.name}" loading="lazy">`;
    const priceTag = cat.price ? `<span class="price-range">${cat.price}</span>` : '';
    html += `<div class="postcard__body"><h3>${cat.name}</h3><p>${priceTag}${priceTag ? ' &middot; ' : ''}${cat.count} piece${cat.count !== 1 ? 's' : ''}</p></div>`;
    html += `</a>`;
  });
  grid.innerHTML = html;
  fadeInImages(grid);
}

function fadeInImages(root) {
  root.querySelectorAll('img[loading="lazy"]').forEach(img => {
    if (img.complete) img.classList.add('loaded');
    else img.addEventListener('load', () => img.classList.add('loaded'));
  });
}

// Boot
document.addEventListener('DOMContentLoaded', () => {
  initProductsPage();
  initFeaturedGrid();
});
